name: ayni_sdk_example
description: Example Flutter app for the ayni_sdk package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  ayni_sdk: ^0.2.0
  flutter:
    sdk: flutter
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
