name: better_fullstack_app
description: "ayni mobile application"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  ayni_sdk: 0.2.0
  archive: ^4.3.0
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  path_provider: ^2.1.6
  share_plus: ^13.3.1
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/validation/experiment_plan.json
